### ISSUE TITLE
TypeError: getoutput() got an unexpected keyword argument 'encoding'

### ISSUE THREAD

**Issue by faveoled** [codelif/touchpad-visualizer#1]
Ubuntu 22.04
```
$ ./touchme 
Traceback (most recent call last):
  File "/home/user/Dev/Python/touchpad-visualizer/./touchme", line 14, in <module>
    DEVICE = get_touchpad_device()
  File "/home/user/Dev/Python/touchpad-visualizer/libinput.py", line 103, in get_touchpad_device
    libinput_devices(),
  File "/home/user/Dev/Python/touchpad-visualizer/libinput.py", line 77, in libinput_devices
    devices_stdout = subprocess.getoutput(
TypeError: getoutput() got an unexpected keyword argument 'encoding'
```

**Comment by codelif** [comment]
Are you in `input` group? This requires `input` group privileges. Or you could just run with `sudo`.

**Comment by codelif** [comment]
Still, I am not sure why you got this particular error. 

Though I never intended for anyone else to use this. But If people are noticing this project I might as well clean it up and add a README.

**Comment by faveoled** [comment]
> Are you in `input` group?

$ getent group | grep input
input:x:107:user



> But If people are noticing this project I might as well clean it up and add a README.

I'd wish to have a screenshot

**Comment by codelif** [comment]
> I'd wish to have a screenshot

Of what?

**Comment by faveoled** [comment]
> Of what?

How the app looks

**Comment by codelif** [comment]
Gimme 5 minutes. Though its pretty barebones.

**Comment by codelif** [comment]
https://github.com/codelif/touchpad-visualizer/assets/68972644/5585b478-1098-48ad-8107-2aad507e1caa

**Comment by faveoled** [comment]
Nice. What python version do you use?

**Comment by codelif** [comment]
3.11.7

**Comment by codelif** [comment]
I think I got it. The encoding parameter was added in 3.11 for the `getoutput` function.

I think `Ubuntu 22.04` ships with 3.10, so maybe that's the problem. I think a temporary fix would be to just remove that encoding parameter. 

I added that because many devices have Chinese characters in their names, so applying a utf-8 encoding would prevent an error.

I didn't know, this was a recently added feature, I try keep my scripts backward compatible. :p

**Comment by faveoled** [comment]
> I think `Ubuntu 22.04` ships with 3.10, so maybe that's the problem. I think a temporary fix would be to just remove that encoding parameter.

Got this:
```
$ ./touchme 
Traceback (most recent call last):
  File "/home/user/Dev/Python/touchpad-visualizer/./touchme", line 14, in <module>
    DEVICE = get_touchpad_device()
  File "/home/user/Dev/Python/touchpad-visualizer/libinput.py", line 103, in get_touchpad_device
    libinput_devices(),
  File "/home/user/Dev/Python/touchpad-visualizer/libinput.py", line 92, in libinput_devices
    devices[devices_index].update({key: value})
IndexError: list index out of range
```

**Comment by codelif** [comment]
Could you check the output of the command `libinput list-devices`?

**Comment by faveoled** [comment]
Wasn't installed. Installed and now app works fine :+1:

**Comment by codelif** [comment]
Thanks for trying out. It was really insightful for me.
